<?php require 'application/layouts/header.phtml'; ?>

<form method="post" action="/index.php?controller=calculator&action=<?php echo $action; ?>">


    <input type="number" name="op1">
    <input type="number" name="op2"> <br>
    <input type="number" name="op3">
    <input type="number" name="op4"> <br>
    <input type="submit" value="ok">
</form>

<?php require 'application/layouts/footer.phtml'; ?>

